Add an opt-in `require-md-extension` option (#13)
This requires local relative links to use `.md` instead of `.html`.
This can be useful for repositories that want to ensure that they're
viewable from a GitHub preview, not only the rendered MdBook.

Example of the new error:
```
error: Local links must use the `.md` extension because `require-md-extension` is enabled
    ┌─ chapter_1.md:4:48
    │
  4 │ [This links to itself using the HTML extension](./chapter_1.html)
    │                                                 ^^^^^^^^^^^^^^^^ Local links must use the `.md` extension because `require-md-extension` is enabled
```